config/routes.rb
Rails.application.routes.draw do
  devise_for :creators
  resources :users
  root 'users#index'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :users
end

app/models/creator.rb
class Creator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
	extend FriendlyId
  	friendly_id :name, use: :slugged
	belongs_to :category

	has_attached_file :image, styles: { large: "1000x1000#", medium: "550x550#", thumb: "150x150#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_creator!, except: [:index, :show]
	def index
		if params[:category].blank?
			@users = User.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
		else
			@category_id = Category.find_by(name: params[:category]).id
			@users = User.where(category_id: @category_id).order("created_at DESC").paginate(page: params[:page], per_page: 5)
		end
	end

	def show

	end

	def create 
		@user = User.new(users_params)

		if @user.save
			redirect_to @user
		else
			render "new"
		end
	end

	def new 
		@user = User.new
	end

	def edit
	end

	def update
		if @user.update(users_params)
			redirect_to @user
		else
			render "edit"
		end
	end

	def destroy
		@user.destroy
		redirect_to root_path

	end

	private 

	def users_params
		params.require(:user).permit(:name, :bio, :category_id, :category_name, :image, :slug)
	end

	def find_user
		@user = User.friendly.find(params[:id])
	end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title CloudFactory PeerReview
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
  %link{:href => "https://fonts.googleapis.com/css?family=Raleway:400,500,700", :rel => "stylesheet"}/
  %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/6.0.0/normalize.css", :rel => "stylesheet"}/
  %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
  %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %link{:href => "https://www.cloudfactory.com/hs-fs/hub/351374/file-457736618-png/img/favicon.png?t=1500362650098", :rel => "shortcut icon"}/
  %link{:href => "https://s3.amazonaws.com/profile-cloudfactory/cf-favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}/

- if notice
  %p.notice= notice
- elsif alert
  %p.alert= alert

%body
  = yield

app/views/users/_form.html.haml
= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f|
	.skinny_wrapper
		.dropdown
			= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose Project" }, class: "dropbtn"
		%br/
		= f.input :name, label: "Name"
		%br/
		= f.input :bio, label: "Bio Info", class: "textarea"
		%br/
		= f.input :image, as: :file
		%br/
		= f.button :submit, class: "button_2"

app/views/users/edit.html.haml
%h1 Edit User

= render 'form'

= link_to "Back", root_path

app/views/users/index.html.haml
%div.wrapper
	%header.main_header.clearfix
		= link_to image_tag("cf-logo.png"), root_path, class: "logo"
		.logo
			= link_to root_path do
				%h1
					Review
					%span Peers
		%a.menu{:href => "#"}
			%i.fa.fa-bars		
		%nav.main_nav
			- Category.all.each do |category|
				= link_to category.name, users_path(category: category.name), class: "current"
			- if creator_signed_in?
				= link_to "New User", new_user_path, class: "new"
				= link_to "Sign Out", destroy_creator_session_path, method: :delete

	- @users.each do |user|
		%ul#timeline
			= link_to user do
				%li.listing.clearfix
					%div.image_wrapper
						= image_tag user.image.url(:thumb)
					%div.info
						%span.user_name= user.name
						%span.bio_info
						%div.location
							%span •
							Nairobi, Kenya
					%span.project_type.p_1= user.category.name
	=will_paginate @users

%footer#main_footer
	%p.copyright © 2017 Review App. All Rights Reserved
	%p.nav
		%a{:href => "https://www.facebook.com/CloudFactoryKenyaLtd/"}
			%i.fa.fa-facebook-square
		%a{:href => "https://www.facebook.com/CloudFactoryHQ"}
			%i.fa.fa-twitter-square
		%a{:href => "https://plus.google.com/+CloudfactoryHQ"}
			%i.fa.fa-google-plus-square

app/views/users/new.html.haml
.single_wrapper
	%h1.title New User

	= render 'form'

app/views/users/show.html.haml
.single_wrapper
	= image_tag @user.image.url(:medium)
	.bio
		%h3= @user.name
		.peer_icons
			%i.fa.fa-phone-square{"aria-hidden" => "true"}
			%i.fa.fa-envelope{"aria-hidden" => "true"}
			%i.fa.fa-skype{"aria-hidden" => "true"}
		%p= @user.bio
		%br/

		.typeform-share.button
			%a.typeform-share.button.evaluate{"data-mode" => "popup", :href => "https://alex1631.typeform.com/to/q6SAnI", :target => "_blank"} Evaluate
		%br/
		
		#admin_links
			= link_to "Home", root_path, id: "links"
			- if creator_signed_in?
				= link_to "Edit", edit_user_path, id: "links"
				= link_to "Delete", user_path(@user), method: :delete, data: { confirm: "Are you sure?" }, id: "links"

		:javascript
			(function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm_share", b="https://embed.typeform.com/"; if(!gi.call(d,id)){ js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })()